[package]
name = "simple-chunk-allocator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libm = "0.2"
log = "0.4"
spin = "0.9"

[dev-dependencies]
simple_logger = "2.1"
rand = "0.8"
x86 = "0.46"
