# With this file, another toolchain to the currently selected one will be used.
# https://rust-lang.github.io/rustup/overrides.html

[toolchain]
channel = "nightly"
# see https://rust-lang.github.io/rustup/concepts/components.html
components = ["rustfmt", "rustc", "cargo", "rust-std", "rust-docs", "clippy" ]
